version: 0.2.0.{build}
image: Visual Studio 2017
configuration: Release
platform:
  - Win32
  - x64
init:
  - if %platform%==x64 set CMAKE_GENERATOR_PLATFORM=x64
before_build:
  - mkdir build-%PLATFORM%
  - cd build-%PLATFORM%
  - cmake .. -G"Visual Studio 15 2017" -DCMAKE_GENERATOR_PLATFORM=%CMAKE_GENERATOR_PLATFORM% -DBUILD_SHARED_LIBS=ON
build_script:
  - cmake --build . --config %configuration%
  - cpack -G ZIP
artifacts:
  - path: build-%PLATFORM%\*.zip
    name: library
deploy:
  description: 'Stable'
  provider: GitHub
  auth_token:
    secure: TvbsyEHHE9ccCWNNLZvD/c0OCSynEWNX3HFDXPcDw42bsXAu11tFfpjpF+DsSkh+
  artifact: library
  draft: false
  prerelease: false
