jobs:
  - job: Ubuntu_CMake
    pool:
      vmImage: 'Ubuntu-16.04'
    steps:
    - script: |
        mkdir build
    - task: CMake@1
      inputs:
        workingDirectory: 'build'
        cmakeArgs: '-DBUILD_SHARED_LIBS=ON ..'
