jobs:
  - job: Ubuntu
    pool:
      vmImage: 'Ubuntu-16.04'
    steps:
    - script: |
        mkdir build
    - task: CMake@1
      inputs:
        workingDirectory: 'build'
        cmakeArgs: '-DBUILD_SHARED_LIBS=ON ..'
    - script: |
        cd build
        cmake --build .

  - job: Windows
    pool:
      vmImage: 'vs2017-win2016'
    steps:
    - script: |
        mkdir build
    - task: CMake@1
      inputs:
        workingDirectory: 'build'
        cmakeArgs: '-DBUILD_SHARED_LIBS=ON ..'
    - script: |
        cd build
        cmake --build .

  - job: macOS
    pool:
      vmImage: 'macOS-10.13'
    steps:
    - script: |
        mkdir build
    - task: CMake@1
      inputs:
        workingDirectory: 'build'
        cmakeArgs: '-DBUILD_SHARED_LIBS=ON ..'
    - script: |
        cd build
        cmake --build .
